### PR TITLE
Fixed variable misname and deprecated ffmpeg constants

### PR DESCRIPTION
**Pull request by bravech**
I know this is a bit of an old repo, but fixing this would make it much easier for noobies (like me) to figure out how to install this.

### CODE REVIEW

**Comment by sakshamjindal** [comment]
@uoip Please merge this PR

**Comment by scimad** [comment]
Fixes #37. Consider merging.

**Comment by plasticuproject** [comment]
This repo hasn't had a commit or merge in 3 years lol. Multiple people have submitted PRs for the same thing. It's dead. Try a fork or forking yourself.

**Comment by scimad** [comment]
> This repo hasn't had a commit or merge in 3 years lol. Multiple people have submitted PRs for the same thing. It's dead. Try a fork or forking yourself.

Haha, thank you. PR from @bravech served my purpose.

**Comment by leekt0124** [comment]
This PR works for my ubuntu20 system. Thanks a lot!

**Comment by ErikOrjehag** [comment]
@bravech thank you thank you thank you :D

**Pull request closed without merging**
